include ../../../Makefile.config

OP	= $(LLVM_PASS) -O3  -x cuda --cuda-gpu-arch=sm_60 -g -DFPC_ERRORS_DONT_ABORT

#LINK	= -L${CUDA_PATH}/lib64/ -lcuda -lcudart

all:
	$(CC) -c compute.cu $(OP)

clean:
	rm *.o *.ll *.bc main
