include ../../../Makefile.config

OP	= $(LLVM_PASS) -O0  -x cuda --cuda-gpu-arch=sm_60 -g
LINK	= -L$(shell ../get_cuda_lib_path.sh) -lcuda -lcudart

all:
	$(CC) -c dot_product.cu $(OP)
	$(CC) -c main.cu $(OP)
	$(CC) -o main dot_product.o main.o $(LINK)

clean:
	rm *.o main
