# Set LLVM_PATH here or in the environment
#export CLANG++=clang++-mp-3.9
#export CLANG=clang-mp-3.9
#export LLVM-CONFIG=llvm-config-mp-3.9
#export LLVM_PATH=/opt/local/libexec/llvm-3.9

# C++ compiler
CXX		= $(LLVM_PATH)/bin/clang++

# llvm-config location
LLVM_CONFIG     = $(LLVM_PATH)/bin/llvm-config

# Passed to compiler
SRC_DIR		?= $(PWD)
COMMON_FLAGS	= -Wall -O3 -g -std=c++11
LDFLAGS		+= $(shell $(LLVM_CONFIG) --ldflags)
CXXFLAGS	+= $(COMMON_FLAGS) $(shell $(LLVM_CONFIG) --cxxflags) -fPIC
CPPFLAGS	+= $(shell $(LLVM_CONFIG) --cppflags) -I$(SRC_DIR)

ifeq ($(shell uname),Darwin)
SHARED_LIB_OPT	= -bundle -undefined dynamic_lookup
else
SHARED_LIB_OPT  = -shared -Wl, -O1
endif

# Installation path
prefix		= ./lib
