# Set LLVM_PATH here or in the environment
#export CLANG++=clang++-mp-9.0
#export CLANG=clang-mp-9.0
#export LLVM_CONFIG=/llvm-config
#export LLVM_PATH=/Users/lagunaperalt1/projects/applications/llvm/install-llvm-9.0.1
export LLVM_PATH=/opt/local

# C++ compiler
CXX		= $(LLVM_PATH)/bin/clang++
#CXX		= clang++-mp-12

# llvm-config location
LLVM_CONFIG     = $(LLVM_PATH)/bin/llvm-config
#LLVM_CONFIG     = llvm-config-mp-12

APPLE_LDFLAGS =-Wl,-flat_namespace -Wl,-undefined -Wl,suppress

# Passed to compiler
SRC_DIR		?= $(PWD)
COMMON_FLAGS	= -Wall -O3 -g -std=c++11
LDFLAGS		+= $(shell $(LLVM_CONFIG) --ldflags) $(APPLE_LDFLAGS)
CXXFLAGS	+= $(COMMON_FLAGS) $(shell $(LLVM_CONFIG) --cxxflags) -fPIC -DFPC_DEBUG
CPPFLAGS	+= $(shell $(LLVM_CONFIG) --cppflags) -I$(SRC_DIR)

ifeq ($(shell uname),Darwin)
SHARED_LIB_OPT	= -bundle -undefined dynamic_lookup
else
SHARED_LIB_OPT  = -shared -Wl, -O1
endif

# Installation path
prefix		= ./lib
