include ../../../Makefile.config

OP	= $(CLANG_PASS) -emit-llvm -O0 -x cuda --cuda-gpu-arch=sm_60 -g
THRESHOLD	= -DFPC_DANGER_ZONE_PERCENT=0.05
REPORTS = -DFPC_ERRORS_DONT_ABORT

all:
	cp dot_product.cu.orig dot_product.cu
	cp main.cu.orig main.cu
	$(CC) $(OP) -c dot_product.cu
	$(CC) $(OP) -c main.cu
	#$(CC) -o main dot_product.o main.o $(LINK)
	nvcc $(INC_RUNTIME_PLUGIN) $(THRESHOLD) $(REPORTS) -arch=sm_60 -O0 -c dot_product.cu
	nvcc $(INC_RUNTIME_PLUGIN) $(THRESHOLD) $(REPORTS) -arch=sm_60 -O0 -c main.cu
	nvcc -o main dot_product.o main.o

clean:
	rm -rf *.cu *.o main __pycache__
