
# Config file for tests

CC		= clang++
FPCHECKER_PATH	= $(PWD)/../../../..

ifeq ($(shell uname),Darwin)
SHARED_LIB_NAME	= libfpchecker.dylib
PLUGIN_LIB_NAME	= libfpchecker_plugin.dylib
else
SHARED_LIB_NAME	= libfpchecker.so
PLUGIN_LIB_NAME = libfpchecker_plugin.so
endif

INC_RUNTIME	= -include Runtime.h -I$(FPCHECKER_PATH)/src
INC_RUNTIME_PLUGIN     = -include Runtime_plugin.h -I$(FPCHECKER_PATH)/src

LLVM_PASS       = -Xclang -load -Xclang $(FPCHECKER_PATH)/build/$(SHARED_LIB_NAME) \
		$(INC_RUNTIME)

CLANG_PASS	= -Xclang -load -Xclang $(FPCHECKER_PATH)/build/$(PLUGIN_LIB_NAME) \
		-Xclang -plugin -Xclang instrumentation_plugin \
		$(INC_RUNTIME)
