
# Config file for tests

CC		= clang++
FPCHECKER_PATH	= $(PWD)/../../..

ifeq ($(shell uname),Darwin)
SHARED_LIB_NAME  = libfpchecker.dylib
else
SHARED_LIB_NAME  = libfpchecker.so
endif

LLVM_PASS       = -Xclang -load -Xclang $(FPCHECKER_PATH)/build/$(SHARED_LIB_NAME) \
		-include Runtime.h -I$(FPCHECKER_PATH)/src


