
# Config file for tests

CC		= $(LLVM_PATH)/bin/clang++
FPCHECKER_PATH	= $(PWD)/../../..
LLVM_PASS       = -Xclang -load -Xclang $(FPCHECKER_PATH)/build/libfpchecker.dylib \
		-include Runtime.h -I$(FPCHECKER_PATH)/src


