
# Config file for tests

CC		= clang++-mp-12
FPCHECKER_PATH	= $(PWD)/../../../..

ifeq ($(shell uname),Darwin)
SHARED_LIB_NAME	= libfpchecker_cpu.so
else
SHARED_LIB_NAME	= libfpchecker_cpu.so
endif

INC_RUNTIME	= -include Runtime_cpu.h -I$(FPCHECKER_PATH)/src

LLVM_PASS       = -Xclang -load -Xclang $(FPCHECKER_PATH)/src/$(SHARED_LIB_NAME) \
		$(INC_RUNTIME)

