include ../../../Makefile.config

OP_LEVEL = -O0
OP	= $(CLANG_PASS) -emit-llvm -x cuda -nocudalib --cuda-gpu-arch=sm_60 -g $(OP_LEVEL)

LINK	= -L${CUDA_PATH}/lib64/ -lcuda -lcudart

all:
	cp -rf src/src/compute.cu.orig src/src/compute.cu
	$(CC) -c src/src/compute.cu $(OP) 

clean:
	rm -rf *.o __pycache__ *.cu
