
# Config file for tests

CC		= $(LLVM_PATH)/bin/clang++
FPCHECKER_PATH	= ../../../..
LLVM_PASS       = -Xclang -load -Xclang $(FPCHECKER_PATH)/src/libfpchecker.so \
		-include Runtime_int.h -I$(FPCHECKER_PATH)/src


