include ../../Makefile.config

OP	= $(LLVM_PASS) -O2  -x cuda --cuda-gpu-arch=sm_60 -g -DFPC_ERRORS_DONT_ABORT
LINK	= -L${CUDA_PATH}/lib64/ -lcuda -lcudart

all:
	$(CC) -c dot_product.cu $(OP)
	$(CC) -c main.cu $(OP)
	$(CC) -o main dot_product.o main.o $(LINK)

clean:
	rm *.o *.bc *.ll *.core main
