include ../../../Makefile.config

OP_LEVEL = -O0
OP	= $(CLANG_PASS) -std=c++11 -emit-llvm -x cuda -nocudalib --cuda-gpu-arch=sm_60 -g $(OP_LEVEL)

LINK	= -L${CUDA_PATH}/lib64/ -lcuda -lcudart

all:
	cp -rf compute.cpp.orig compute.cpp
	$(CC) $(OP) -c compute.cpp

clean:
	rm -rf *.o __pycache__ *.cu *.cpp
