include ../../../Makefile.config

OP_LEVEL = -O0

OP	= $(LLVM_PASS) $(OP_LEVEL) -std=c++11 -x cuda --cuda-gpu-arch=sm_60 -g -I$(RAJA_PATH)/include -DFPC_ERRORS_DONT_ABORT
LINK	= -L$(shell ../get_cuda_lib_path.sh) -lcuda -lcudart \
	-L$(RAJA_PATH)/lib -lRAJA
all:
	$(CC) $(OP) -c dot_product_raja.cpp
	$(CC) -o main dot_product_raja.o $(LINK)

clean:
	rm *.o *.core main 
