
CC		= $(LLVM_PATH)/bin/clang++

LLVM_PASS       = -Xclang -load -Xclang $(PWD)/../../../src/libcudakernels.so \
-include Runtime.h -I$(PWD)/../../../src -DFPC_ERRORS_DONT_ABORT

OP_LEVEL = -O0

OP	= $(LLVM_PASS) $(OP_LEVEL) -std=c++11 -x cuda --cuda-gpu-arch=sm_60 -g -I$(RAJA_PATH)/include
LINK	= -L${CUDA_PATH}/lib64/ -lcuda -lcudart \
	-L$(RAJA_PATH)/lib -lRAJA
all:
	$(CC) $(OP) -c dot_product_raja.cpp
	$(CC) -o dot_product_raja dot_product_raja.o $(LINK)

clean:
	rm *.o *.core dot_product_raja
