
CXX		= $(LLVM_PATH)/bin/clang++
FPCHECKER_PATH	= $(PWD)/../../../../
LLVM_PASS       = -Xclang -load -Xclang $(FPCHECKER_PATH)/src/libfpchecker.so \
		-include Runtime_int.h -I$(FPCHECKER_PATH)/src

OP	= $(LLVM_PASS) -O0

CXX = $(LLVM_PATH)/bin/clang++

all:
	$(CXX) -c $(OP) comp.cpp
	$(CXX) -c $(OP) main.cpp
	$(CXX) -o main main.o comp.o

clean:
	rm -rf main *.o *.bc *.ll *.pyc *.json
