include ../../../Makefile.config

OP_LEVEL = -O0
OP	= $(CLANG_PASS) -emit-llvm -x cuda -nocudalib --cuda-gpu-arch=sm_60 -g $(OP_LEVEL)

LINK	= -L${CUDA_PATH}/lib64/ -lcuda -lcudart

all:
	cp -rf compute.cu.orig compute.cu
	$(CC) -c compute.cu $(OP)
	nvcc $(INC_RUNTIME_PLUGIN) -arch=sm_60 -c compute.cu

clean:
	rm -rf *.o __pycache__ *.cu
